CREATE DATABASE DB_MEMBER;
USE DB_MEMBER;

CREATE TABLE TBL_MEMBER(
   M_ID VARCHAR(20) NOT NULL UNIQUE, 
    M_PW VARCHAR(100) NOT NULL,
    M_MAIL VARCHAR(50) NOT NULL,
    M_PHONE VARCHAR(50) NOT NULL,
    M_PROFILE_THUM VARCHAR(50),
    M_REG_DATE DATETIME,
    M_MOD_DATE DATETIME,
    PRIMARY KEY(M_ID)
);

SELECT * FROM TBL_MEMBER;
DELETE FROM TBL_MEMBER;
DROP TABLE TBL_MEMBER;

CREATE TABLE TBL_PROFILE_THUMS(
   PT_NO INT AUTO_INCREMENT, 
    M_ID VARCHAR(20) NOT NULL,
    PT_THUM VARCHAR(50) NOT NULL,
    PT_VISIBLE tinyint DEFAULT 1,
    PT_ENABLE tinyint DEFAULT 1,
    PT_REG_DATE DATETIME,
    PT_MOD_DATE DATETIME,
    PRIMARY KEY(PT_NO)
);

SELECT * FROM TBL_PROFILE_THUMS;
DELETE FROM TBL_PROFILE_THUMS;
DROP TABLE TBL_PROFILE_THUMS;

SELECT * FROM TBL_PROFILE_THUMS 
WHERE M_ID = 'gildong' 
ORDER BY PT_NO ASC;